# Voice for Bharat - Simple Deployment Script
# This script deploys backend to AWS and prepares frontend

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Voice for Bharat - Automated Deployment" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check prerequisites
Write-Host "Checking prerequisites..." -ForegroundColor Yellow

# Check AWS CLI
try {
    $awsVersion = aws --version 2>&1
    Write-Host "[OK] AWS CLI: $awsVersion" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] AWS CLI not found. Please install from: https://aws.amazon.com/cli/" -ForegroundColor Red
    exit 1
}

# Check SAM CLI
try {
    $samVersion = sam --version 2>&1
    Write-Host "[OK] SAM CLI: $samVersion" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] SAM CLI not found. Please install from: https://aws.amazon.com/serverless/sam/" -ForegroundColor Red
    exit 1
}

# Check Python
try {
    $pythonVersion = python --version 2>&1
    Write-Host "[OK] Python: $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Python not found. Please install Python 3.11 or higher." -ForegroundColor Red
    exit 1
}

# Check AWS credentials
try {
    $awsIdentity = aws sts get-caller-identity 2>&1 | ConvertFrom-Json
    Write-Host "[OK] AWS Credentials configured for Account: $($awsIdentity.Account)" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] AWS credentials not configured. Run: aws configure" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "All prerequisites met!" -ForegroundColor Green
Write-Host ""

# ==============================================
# Part 1: Deploy Backend to AWS
# ==============================================
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Part 1: Deploying Backend to AWS" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Navigate to backend
Set-Location backend

# Build Lambda functions
Write-Host "Building Lambda functions..." -ForegroundColor Yellow
sam build

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Build failed!" -ForegroundColor Red
    Set-Location ..
    exit 1
}

Write-Host "[SUCCESS] Build completed!" -ForegroundColor Green
Write-Host ""

# Deploy to AWS
Write-Host "Deploying to AWS..." -ForegroundColor Yellow
Write-Host "This will take 20-30 minutes. Please be patient..." -ForegroundColor Yellow
Write-Host ""

sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Deployment failed!" -ForegroundColor Red
    Set-Location ..
    exit 1
}

Write-Host "[SUCCESS] Backend deployed!" -ForegroundColor Green
Write-Host ""

# Get CloudFormation outputs
Write-Host "Fetching deployment outputs..." -ForegroundColor Yellow
$stackName = "voicebharatai"
$region = "ap-south-1"

try {
    $outputs = aws cloudformation describe-stacks --stack-name $stackName --region $region --query "Stacks[0].Outputs" 2>&1 | ConvertFrom-Json
    
    $apiUrl = ($outputs | Where-Object { $_.OutputKey -eq "VoiceForBharatApiUrl" }).OutputValue
    $wsUrl = ($outputs | Where-Object { $_.OutputKey -eq "VoiceWebSocketApiUrl" }).OutputValue
    $cloudFrontUrl = ($outputs | Where-Object { $_.OutputKey -eq "CloudFrontURL" }).OutputValue
    $userPoolId = ($outputs | Where-Object { $_.OutputKey -eq "CognitoUserPoolId" }).OutputValue
    $clientId = ($outputs | Where-Object { $_.OutputKey -eq "CognitoUserPoolClientId" }).OutputValue
    
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "Backend Deployment Successful!" -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "API Gateway URL:" -ForegroundColor Cyan
    Write-Host $apiUrl -ForegroundColor White
    Write-Host ""
    Write-Host "WebSocket URL:" -ForegroundColor Cyan
    Write-Host $wsUrl -ForegroundColor White
    Write-Host ""
    Write-Host "CloudFront URL:" -ForegroundColor Cyan
    Write-Host $cloudFrontUrl -ForegroundColor White
    Write-Host ""
    Write-Host "Cognito User Pool ID:" -ForegroundColor Cyan
    Write-Host $userPoolId -ForegroundColor White
    Write-Host ""
    Write-Host "Cognito Client ID:" -ForegroundColor Cyan
    Write-Host $clientId -ForegroundColor White
    Write-Host ""
    
    # Create environment file for frontend
    $envContent = @"
# Voice for Bharat - Environment Variables
# Auto-generated by deploy-simple.ps1

# API Configuration
NEXT_PUBLIC_API_URL=$apiUrl
NEXT_PUBLIC_WS_URL=$wsUrl
NEXT_PUBLIC_CLOUDFRONT_URL=$cloudFrontUrl

# AWS Cognito
NEXT_PUBLIC_COGNITO_USER_POOL_ID=$userPoolId
NEXT_PUBLIC_COGNITO_CLIENT_ID=$clientId
NEXT_PUBLIC_COGNITO_REGION=ap-south-1

# Feature Flags
NEXT_PUBLIC_ENABLE_PWA=true
NEXT_PUBLIC_ENABLE_VOICE_ASSISTANT=true
NEXT_PUBLIC_ENABLE_OFFLINE_MODE=true
"@
    
    Set-Location ..
    $envContent | Out-File -FilePath "frontend\web\.env.local" -Encoding UTF8
    
    Write-Host "[SUCCESS] Environment variables saved to frontend/web/.env.local" -ForegroundColor Green
    Write-Host ""
    
    # Save to file for Vercel
    $envContent | Out-File -FilePath "VERCEL_ENV_VALUES.txt" -Encoding UTF8
    Write-Host "[SUCCESS] Environment variables also saved to VERCEL_ENV_VALUES.txt" -ForegroundColor Green
    Write-Host ""
    
} catch {
    Write-Host "[ERROR] Failed to fetch outputs: $_" -ForegroundColor Red
    Set-Location ..
    exit 1
}

# Test backend health
Write-Host "Testing backend health..." -ForegroundColor Yellow
try {
    $healthUrl = "$apiUrl/health"
    $response = Invoke-WebRequest -Uri $healthUrl -Method GET -UseBasicParsing -TimeoutSec 10
    if ($response.StatusCode -eq 200) {
        Write-Host "[SUCCESS] Backend is healthy!" -ForegroundColor Green
    }
} catch {
    Write-Host "[WARNING] Backend health check failed. It might take a few minutes to warm up." -ForegroundColor Yellow
}

Write-Host ""

# ==============================================
# Part 2: Prepare Frontend for Vercel
# ==============================================
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Part 2: Preparing Frontend for Vercel" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Navigate to frontend
Set-Location frontend\web

# Install dependencies
Write-Host "Installing frontend dependencies..." -ForegroundColor Yellow
npm install

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] npm install failed!" -ForegroundColor Red
    Set-Location ..\..
    exit 1
}

Write-Host "[SUCCESS] Dependencies installed!" -ForegroundColor Green
Write-Host ""

# Build frontend locally to verify
Write-Host "Building frontend locally to verify..." -ForegroundColor Yellow
npm run build

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Frontend build failed!" -ForegroundColor Red
    Set-Location ..\..
    exit 1
}

Write-Host "[SUCCESS] Frontend build successful!" -ForegroundColor Green
Write-Host ""

# Navigate back to project root
Set-Location ..\..

# ==============================================
# Part 3: Git Commit and Push
# ==============================================
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Part 3: Committing Changes to Git" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Current git status:" -ForegroundColor Yellow
git status --short

Write-Host ""
$commit = Read-Host "Do you want to commit and push changes? (y/n)"

if ($commit -eq "y" -or $commit -eq "Y") {
    Write-Host "Committing changes..." -ForegroundColor Yellow
    
    git add .
    git commit -m "Complete AWS deployment - Backend live, Frontend ready for Vercel"
    git push origin main
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] Git push failed!" -ForegroundColor Red
        Write-Host "Please push manually: git push origin main" -ForegroundColor Yellow
    } else {
        Write-Host "[SUCCESS] Changes pushed to GitHub!" -ForegroundColor Green
    }
} else {
    Write-Host "[SKIPPED] Git commit skipped. Remember to push changes manually!" -ForegroundColor Yellow
}

Write-Host ""

# ==============================================
# Final Summary
# ==============================================
Write-Host "========================================" -ForegroundColor Green
Write-Host "DEPLOYMENT COMPLETE!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""

Write-Host "Backend Status: DEPLOYED TO AWS" -ForegroundColor Green
Write-Host "Frontend Status: BUILT & READY" -ForegroundColor Green

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Next Steps:" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "1. Deploy Frontend to Vercel:" -ForegroundColor Yellow
Write-Host "   a. Go to https://vercel.com/dashboard" -ForegroundColor White
Write-Host "   b. Click 'Add New Project'" -ForegroundColor White
Write-Host "   c. Import your GitHub repository" -ForegroundColor White
Write-Host "   d. Set Root Directory to: frontend/web" -ForegroundColor White
Write-Host "   e. Copy environment variables from VERCEL_ENV_VALUES.txt" -ForegroundColor White
Write-Host "   f. Click Deploy!" -ForegroundColor White
Write-Host ""

Write-Host "2. Environment variables are ready in:" -ForegroundColor Yellow
Write-Host "   - frontend/web/.env.local (for local development)" -ForegroundColor White
Write-Host "   - VERCEL_ENV_VALUES.txt (copy-paste for Vercel)" -ForegroundColor White
Write-Host ""

Write-Host "3. Test your deployment:" -ForegroundColor Yellow
Write-Host "   Backend: $apiUrl/health" -ForegroundColor White
Write-Host "   Frontend: [Your Vercel URL after deployment]" -ForegroundColor White
Write-Host ""

Write-Host "========================================" -ForegroundColor Green
Write-Host "Voice for Bharat is ready!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
